/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import base.UI;
import java.util.Map;

/**
 *
 * @author MiriamMarie
 */
public class CategoryDetailsWindow extends UI{

    /**
     * Creates new form CategoryDetailsWindow
     */
    public CategoryDetailsWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryDetails_panel = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        name_details = new javax.swing.JLabel();
        description_label = new javax.swing.JLabel();
        category_details = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        parent_label = new javax.swing.JLabel();
        parent_details = new javax.swing.JLabel();
        close_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Category Details");
        setName("Form"); // NOI18N

        categoryDetails_panel.setName("categoryDetails_panel"); // NOI18N

        name_label.setText("Category Name:");
        name_label.setName("name_label"); // NOI18N

        name_details.setText(" ");
        name_details.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        name_details.setName("name_details"); // NOI18N

        description_label.setText("Category Description:");
        description_label.setName("description_label"); // NOI18N

        category_details.setName("category_details"); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        category_details.setViewportView(jTextArea1);

        parent_label.setText("Parent Category:");
        parent_label.setName("parent_label"); // NOI18N

        parent_details.setText(" ");
        parent_details.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        parent_details.setName("parent_details"); // NOI18N

        close_button.setText("Close");
        close_button.setName("close_button"); // NOI18N

        javax.swing.GroupLayout categoryDetails_panelLayout = new javax.swing.GroupLayout(categoryDetails_panel);
        categoryDetails_panel.setLayout(categoryDetails_panelLayout);
        categoryDetails_panelLayout.setHorizontalGroup(
            categoryDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryDetails_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(categoryDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(categoryDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(categoryDetails_panelLayout.createSequentialGroup()
                            .addComponent(parent_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(parent_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(categoryDetails_panelLayout.createSequentialGroup()
                            .addComponent(name_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(name_details, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(categoryDetails_panelLayout.createSequentialGroup()
                            .addComponent(description_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(category_details)))
                    .addComponent(close_button, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        categoryDetails_panelLayout.setVerticalGroup(
            categoryDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryDetails_panelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(categoryDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label)
                    .addComponent(name_details))
                .addGap(18, 18, 18)
                .addGroup(categoryDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description_label)
                    .addComponent(category_details, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(categoryDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parent_label)
                    .addComponent(parent_details))
                .addGap(18, 18, 18)
                .addComponent(close_button)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoryDetails_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoryDetails_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryDetailsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryDetailsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryDetailsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryDetailsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryDetailsWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel categoryDetails_panel;
    private javax.swing.JScrollPane category_details;
    private javax.swing.JButton close_button;
    private javax.swing.JLabel description_label;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel name_details;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel parent_details;
    private javax.swing.JLabel parent_label;
    // End of variables declaration//GEN-END:variables

    @Override
    public Map getFields() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
