/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import base.Database;
import base.UI;
import commands.factory.CommandFactory;
import exceptions.ExecutorException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Category;
import models.Item;
import models.Supplier;
import statics.Executor;

/**
 *
 * @author MiriamMarie
 */
public class EditItemWindow extends UI {

    /**
     * Creates new form EditItemWindow
     */
    public EditItemWindow() {
        initComponents();
        Executor.put("editItem", CommandFactory.createEditItemCommand(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editItem_panel = new javax.swing.JPanel();
        item_label = new javax.swing.JLabel();
        itemName_combo = new javax.swing.JComboBox();
        itemName_radiobutton = new javax.swing.JRadioButton();
        itemName_field = new javax.swing.JTextField();
        itemDescription_radiobutton = new javax.swing.JRadioButton();
        description_scollpane = new javax.swing.JScrollPane();
        itemDescription_field = new javax.swing.JTextArea();
        save_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        itemSupplier_radiobutton = new javax.swing.JRadioButton();
        itemCategory_radiobutton = new javax.swing.JRadioButton();
        itemSupplier_combo = new javax.swing.JComboBox();
        itemCategory_combo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Item");

        item_label.setText("Choose Item to Edit:");

        refreshItemList();
        itemName_combo.setName("itemName_combo"); // NOI18N

        itemName_radiobutton.setLabel("Edit Item Name:");
        itemName_radiobutton.setName("itemName_radiobutton"); // NOI18N
        itemName_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemName_radiobuttonActionPerformed(evt);
            }
        });

        itemName_field.setEnabled(false);
        itemName_field.setName("itemName_field"); // NOI18N

        itemDescription_radiobutton.setLabel("Edit Item Description:");
        itemDescription_radiobutton.setName("itemDescription_radiobutton"); // NOI18N
        itemDescription_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDescription_radiobuttonActionPerformed(evt);
            }
        });

        itemDescription_field.setColumns(20);
        itemDescription_field.setLineWrap(true);
        itemDescription_field.setRows(5);
        itemDescription_field.setEnabled(false);
        itemDescription_field.setName("itemDescription_field"); // NOI18N
        description_scollpane.setViewportView(itemDescription_field);

        save_button.setText("Save");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        itemSupplier_radiobutton.setText("Edit Supplier:");
        itemSupplier_radiobutton.setName("itemSupplier_radiobutton"); // NOI18N

        itemCategory_radiobutton.setText("Edit Category:");
        itemCategory_radiobutton.setName("itemCategory_radiobutton"); // NOI18N

        List<Supplier> supplierList = Database.getSupplierList();
        itemSupplier_combo.setModel(new javax.swing.DefaultComboBoxModel());
        itemSupplier_combo.addItem(new String("--- SELECT ITEM ---"));
        for(Supplier s : supplierList)
        itemSupplier_combo.addItem(s);
        itemSupplier_combo.setEnabled(false);
        itemSupplier_combo.setName("itemSupplier_combo"); // NOI18N

        List<Category> categoryList = Database.getCategoryList();
        itemCategory_combo.setModel(new javax.swing.DefaultComboBoxModel());
        itemCategory_combo.addItem(new String("--- SELECT CATEGORY ---"));
        for(Category c : categoryList)
        itemCategory_combo.addItem(c);
        itemCategory_combo.setEnabled(false);
        itemCategory_combo.setName("itemCategory_combo"); // NOI18N

        javax.swing.GroupLayout editItem_panelLayout = new javax.swing.GroupLayout(editItem_panel);
        editItem_panel.setLayout(editItem_panelLayout);
        editItem_panelLayout.setHorizontalGroup(
            editItem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editItem_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editItem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(editItem_panelLayout.createSequentialGroup()
                        .addGroup(editItem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item_label)
                            .addComponent(itemName_radiobutton))
                        .addGap(20, 20, 20)
                        .addGroup(editItem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(itemName_field)
                            .addComponent(itemName_combo, 0, 208, Short.MAX_VALUE)))
                    .addGroup(editItem_panelLayout.createSequentialGroup()
                        .addComponent(itemDescription_radiobutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editItem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(description_scollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editItem_panelLayout.createSequentialGroup()
                                .addComponent(save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))))
                    .addGroup(editItem_panelLayout.createSequentialGroup()
                        .addComponent(itemSupplier_radiobutton)
                        .addGap(34, 34, 34)
                        .addComponent(itemSupplier_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(editItem_panelLayout.createSequentialGroup()
                        .addComponent(itemCategory_radiobutton)
                        .addGap(28, 28, 28)
                        .addComponent(itemCategory_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        editItem_panelLayout.setVerticalGroup(
            editItem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editItem_panelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(editItem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_label)
                    .addComponent(itemName_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editItem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemName_radiobutton)
                    .addComponent(itemName_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editItem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemDescription_radiobutton)
                    .addComponent(description_scollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(editItem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemSupplier_radiobutton)
                    .addComponent(itemSupplier_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(editItem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemCategory_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemCategory_radiobutton))
                .addGap(18, 18, 18)
                .addGroup(editItem_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_button)
                    .addComponent(cancel_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(editItem_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editItem_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemName_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemName_radiobuttonActionPerformed
        if(itemName_radiobutton.isSelected())
            itemName_field.setEnabled(true);
        else itemName_field.setEnabled(false);
    }//GEN-LAST:event_itemName_radiobuttonActionPerformed

    private void itemDescription_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDescription_radiobuttonActionPerformed
        if(itemDescription_radiobutton.isSelected())
            itemDescription_field.setEnabled(true);
        else itemDescription_field.setEnabled(false);
    }//GEN-LAST:event_itemDescription_radiobuttonActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        try {
            Executor.execute("editItem");
        } catch (ExecutorException ex) {
            Logger.getLogger(EditItemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_save_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void itemSupplier_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSupplier_radiobuttonActionPerformed
        if(itemSupplier_radiobutton.isSelected())
            itemSupplier_combo.setEnabled(true);
        else itemSupplier_combo.setEnabled(false);
    }//GEN-LAST:event_itemSupplier_radiobuttonActionPerformed

    private void itemCategory_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategory_radiobuttonActionPerformed
        // TODO add your handling code here:
        if(itemCategory_radiobutton.isSelected())
            itemCategory_combo.setEnabled(true);
        else itemCategory_combo.setEnabled(false);
    }//GEN-LAST:event_itemCategory_radiobuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditItemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditItemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditItemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditItemWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditItemWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JScrollPane description_scollpane;
    private javax.swing.JPanel editItem_panel;
    private javax.swing.JComboBox itemCategory_combo;
    private javax.swing.JRadioButton itemCategory_radiobutton;
    private javax.swing.JTextArea itemDescription_field;
    private javax.swing.JRadioButton itemDescription_radiobutton;
    private javax.swing.JComboBox itemName_combo;
    private javax.swing.JTextField itemName_field;
    private javax.swing.JRadioButton itemName_radiobutton;
    private javax.swing.JComboBox itemSupplier_combo;
    private javax.swing.JRadioButton itemSupplier_radiobutton;
    private javax.swing.JLabel item_label;
    private javax.swing.JButton save_button;
    // End of variables declaration//GEN-END:variables

    @Override
    public Map getFields() {
        Map fields = new HashMap();
        fields.put(itemDescription_field.getName(), itemDescription_field);
        fields.put(itemName_field.getName(), itemName_field);
        fields.put(itemName_combo.getName(), itemName_combo);
        fields.put(itemSupplier_combo.getName(), itemSupplier_combo);
        fields.put(itemCategory_combo.getName(), itemCategory_combo);
        fields.put(itemCategory_radiobutton.getName(), itemCategory_radiobutton);
        fields.put(itemDescription_radiobutton.getName(), itemDescription_radiobutton);
        fields.put(itemName_radiobutton.getName(), itemName_radiobutton);
        fields.put(itemSupplier_radiobutton.getName(), itemSupplier_radiobutton);
        return fields;
    }
    
    private void refreshItemList(){
        List<Item> itemList = Database.getItemList();
        itemName_combo.setModel(new javax.swing.DefaultComboBoxModel());
        itemName_combo.addItem("--- SELECT ITEM ---");
        for(Item i : itemList)
            itemName_combo.addItem(i);
    }
}
