/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author MiriamMarie
 */
public class EditCategoryWindow extends javax.swing.JFrame {

    /**
     * Creates new form EditCategoryWindow
     */
    public EditCategoryWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editCategory_panel = new javax.swing.JPanel();
        category_label = new javax.swing.JLabel();
        category_combo = new javax.swing.JComboBox();
        editName_radiobutton = new javax.swing.JRadioButton();
        editName_field = new javax.swing.JTextField();
        editDescription_radiobutton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        editDescription_field = new javax.swing.JTextArea();
        editParent_radiobutton = new javax.swing.JRadioButton();
        editParent_combo = new javax.swing.JComboBox();
        ok_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Category");

        category_label.setText("Choose Category to Edit:");

        category_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        category_combo.setName("category_combo"); // NOI18N

        editName_radiobutton.setText("Edit Category Name:");
        editName_radiobutton.setName("editName_radiobutton"); // NOI18N
        editName_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editName_radiobuttonActionPerformed(evt);
            }
        });

        editName_field.setEnabled(false);
        editName_field.setName("editName_field"); // NOI18N

        editDescription_radiobutton.setText("Edit Category Description:");
        editDescription_radiobutton.setName("editDescription_radiobutton"); // NOI18N
        editDescription_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDescription_radiobuttonActionPerformed(evt);
            }
        });

        editDescription_field.setColumns(20);
        editDescription_field.setLineWrap(true);
        editDescription_field.setRows(5);
        editDescription_field.setEnabled(false);
        editDescription_field.setName("editDescription_field"); // NOI18N
        jScrollPane1.setViewportView(editDescription_field);

        editParent_radiobutton.setText("Edit Parent Category:");
        editParent_radiobutton.setName("editParent_radiobutton"); // NOI18N
        editParent_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editParent_radiobuttonActionPerformed(evt);
            }
        });

        editParent_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        editParent_combo.setEnabled(false);
        editParent_combo.setName("editParent_combo"); // NOI18N

        ok_button.setText("OK");

        cancel_button.setText("Cancel");

        javax.swing.GroupLayout editCategory_panelLayout = new javax.swing.GroupLayout(editCategory_panel);
        editCategory_panel.setLayout(editCategory_panelLayout);
        editCategory_panelLayout.setHorizontalGroup(
            editCategory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCategory_panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(editCategory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(editCategory_panelLayout.createSequentialGroup()
                        .addComponent(editName_radiobutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editName_field))
                    .addGroup(editCategory_panelLayout.createSequentialGroup()
                        .addComponent(category_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(category_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editCategory_panelLayout.createSequentialGroup()
                        .addComponent(editParent_radiobutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editParent_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editCategory_panelLayout.createSequentialGroup()
                        .addComponent(editDescription_radiobutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editCategory_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ok_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        editCategory_panelLayout.setVerticalGroup(
            editCategory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCategory_panelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(editCategory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(category_label)
                    .addComponent(category_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCategory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editName_radiobutton)
                    .addComponent(editName_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCategory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editDescription_radiobutton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editCategory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editParent_radiobutton)
                    .addComponent(editParent_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editCategory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok_button)
                    .addComponent(cancel_button))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editCategory_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editCategory_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editName_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editName_radiobuttonActionPerformed
        // TODO add your handling code here:
        if(editName_radiobutton.isSelected())
            editName_field.setEnabled(true);
        else editName_field.setEnabled(false);
    }//GEN-LAST:event_editName_radiobuttonActionPerformed

    private void editDescription_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDescription_radiobuttonActionPerformed
        // TODO add your handling code here:
        if(editDescription_radiobutton.isSelected())
            editDescription_field.setEnabled(true);
        else editDescription_field.setEnabled(false);
    }//GEN-LAST:event_editDescription_radiobuttonActionPerformed

    private void editParent_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editParent_radiobuttonActionPerformed
        // TODO add your handling code here:
        if(editParent_radiobutton.isSelected())
            editParent_combo.setEnabled(true);
        else editParent_combo.setEnabled(false);
    }//GEN-LAST:event_editParent_radiobuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCategoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCategoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCategoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCategoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCategoryWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JComboBox category_combo;
    private javax.swing.JLabel category_label;
    private javax.swing.JPanel editCategory_panel;
    private javax.swing.JTextArea editDescription_field;
    private javax.swing.JRadioButton editDescription_radiobutton;
    private javax.swing.JTextField editName_field;
    private javax.swing.JRadioButton editName_radiobutton;
    private javax.swing.JComboBox editParent_combo;
    private javax.swing.JRadioButton editParent_radiobutton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok_button;
    // End of variables declaration//GEN-END:variables
}
