/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import base.UI;
import commands.factory.CommandFactory;
import exceptions.ExecutorException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import statics.Executor;
import static ui.MainWindow.edit;

/**
 *
 * @author MiriamMarie
 */
public class EditWindow extends UI {
    static UI supplier, item, category;
    /**
     * Creates new form EditWindow
     */
    public EditWindow() {
        initComponents();
        initWindow();
    }
    
    private void initWindow(){
        supplier = new EditSupplierWindow();
        item = new EditItemWindow();
        category = new EditCategoryWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editWindow_panel = new javax.swing.JPanel();
        editSupplier_button = new javax.swing.JButton();
        editItem_button = new javax.swing.JButton();
        editCategory_button = new javax.swing.JButton();
        ok_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit ");

        editSupplier_button.setText("Edit Supplier");
        editSupplier_button.setName("editSupplier_button"); // NOI18N
        editSupplier_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSupplier_buttonActionPerformed(evt);
            }
        });

        editItem_button.setText("Edit Item");
        editItem_button.setName("editItem_button"); // NOI18N
        editItem_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editItem_buttonActionPerformed(evt);
            }
        });

        editCategory_button.setText("Edit Category");
        editCategory_button.setName("editCategory_button"); // NOI18N
        editCategory_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCategory_buttonActionPerformed(evt);
            }
        });

        ok_button.setText("OK");
        ok_button.setName("ok_button"); // NOI18N
        ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editWindow_panelLayout = new javax.swing.GroupLayout(editWindow_panel);
        editWindow_panel.setLayout(editWindow_panelLayout);
        editWindow_panelLayout.setHorizontalGroup(
            editWindow_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editWindow_panelLayout.createSequentialGroup()
                .addGroup(editWindow_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editWindow_panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(editSupplier_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editItem_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editCategory_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editWindow_panelLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(ok_button)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        editWindow_panelLayout.setVerticalGroup(
            editWindow_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editWindow_panelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(editWindow_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSupplier_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editItem_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCategory_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ok_button)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editWindow_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editWindow_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editSupplier_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSupplier_buttonActionPerformed
        this.dispose();
        if(!supplier.isVisible())
            supplier.setVisible(true);
        supplier.setAlwaysOnTop(true);
        supplier.setAlwaysOnTop(false);
    }//GEN-LAST:event_editSupplier_buttonActionPerformed

    private void editItem_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editItem_buttonActionPerformed
        this.dispose();
        if(!item.isVisible())
            item.setVisible(true);
        item.setAlwaysOnTop(true);
        item.setAlwaysOnTop(false);
    }//GEN-LAST:event_editItem_buttonActionPerformed

    private void editCategory_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCategory_buttonActionPerformed
        this.dispose();
        if(!category.isVisible())
            category.setVisible(true);
        category.setAlwaysOnTop(true);
        category.setAlwaysOnTop(false);
    }//GEN-LAST:event_editCategory_buttonActionPerformed

    private void ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buttonActionPerformed
        new MainWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ok_buttonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editCategory_button;
    private javax.swing.JButton editItem_button;
    private javax.swing.JButton editSupplier_button;
    private javax.swing.JPanel editWindow_panel;
    private javax.swing.JButton ok_button;
    // End of variables declaration//GEN-END:variables

    @Override
    public Map getFields() {
        Map fields = new HashMap();
        return fields;
    }
}
