/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import base.UI;
import java.util.Map;
import models.Category;
import models.Item;

/**
 *
 * @author MiriamMarie
 */
public class ViewCategoryDetailsWindow extends UI{
    Item selectedItem;
    
    /**
     * Creates new form CategoryDetailsWindow
     */
    public ViewCategoryDetailsWindow(Item i) {
        initComponents();
        selectedItem = i;
        initText();
    }
    
    private void initText(){
        Category category = selectedItem.getCategory();
        category_details.setText(category.getDescription());
        name_details.setText(category.getName());
        parent_details.setText(category.getParentcategory().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryDetails_panel = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        name_details = new javax.swing.JLabel();
        description_label = new javax.swing.JLabel();
        JScrollPane1 = new javax.swing.JScrollPane();
        category_details = new javax.swing.JTextArea();
        parent_label = new javax.swing.JLabel();
        parent_details = new javax.swing.JLabel();
        close_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Category Details");
        setName("Form"); // NOI18N

        categoryDetails_panel.setName("categoryDetails_panel"); // NOI18N

        name_label.setText("Category Name:");
        name_label.setName("name_label"); // NOI18N

        name_details.setText(" ");
        name_details.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        name_details.setName("name_details"); // NOI18N

        description_label.setText("Category Description:");
        description_label.setName("description_label"); // NOI18N

        JScrollPane1.setName("JScrollPane1"); // NOI18N

        category_details.setEditable(false);
        category_details.setColumns(20);
        category_details.setLineWrap(true);
        category_details.setRows(5);
        category_details.setName("category_details"); // NOI18N
        JScrollPane1.setViewportView(category_details);

        parent_label.setText("Parent Category:");
        parent_label.setName("parent_label"); // NOI18N

        parent_details.setText(" ");
        parent_details.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        parent_details.setName("parent_details"); // NOI18N

        close_button.setText("Close");
        close_button.setName("close_button"); // NOI18N
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout categoryDetails_panelLayout = new javax.swing.GroupLayout(categoryDetails_panel);
        categoryDetails_panel.setLayout(categoryDetails_panelLayout);
        categoryDetails_panelLayout.setHorizontalGroup(
            categoryDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryDetails_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(categoryDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(categoryDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(categoryDetails_panelLayout.createSequentialGroup()
                            .addComponent(parent_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(parent_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(categoryDetails_panelLayout.createSequentialGroup()
                            .addComponent(name_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(name_details, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(categoryDetails_panelLayout.createSequentialGroup()
                            .addComponent(description_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JScrollPane1)))
                    .addComponent(close_button, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        categoryDetails_panelLayout.setVerticalGroup(
            categoryDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryDetails_panelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(categoryDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label)
                    .addComponent(name_details))
                .addGap(18, 18, 18)
                .addGroup(categoryDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description_label)
                    .addComponent(JScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(categoryDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parent_label)
                    .addComponent(parent_details))
                .addGap(18, 18, 18)
                .addComponent(close_button)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoryDetails_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoryDetails_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_close_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JPanel categoryDetails_panel;
    private javax.swing.JTextArea category_details;
    private javax.swing.JButton close_button;
    private javax.swing.JLabel description_label;
    private javax.swing.JLabel name_details;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel parent_details;
    private javax.swing.JLabel parent_label;
    // End of variables declaration//GEN-END:variables

    @Override
    public Map getFields() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
