/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import base.Database;
import base.UI;
import java.util.List;
import java.util.Map;
import models.Item;

/**
 *
 * @author MiriamMarie
 */
public class ViewItemDetailsWindow extends UI {
    UI supplier, category;
    Item selectedItem;
    
    /**
     * Creates new form ItemDetailsWindow
     * @param selectedRow the selected row index in the table
     */
    public ViewItemDetailsWindow(int selectedRow) {
        initComponents();
        setSelectedItem(selectedRow);
        initWindow();
        initText();
    }
    
    private void initText(){
        name_details.setText(selectedItem.getName());
        description_details.setText(selectedItem.getDescription());
        supplier_details.setText(selectedItem.getSupplier().getName());
        category_details.setText(selectedItem.getCategory().getName());
    }
    
    private void setSelectedItem(int selectedRow){
        List<Item> itemList = Database.getItemList();
        selectedItem = itemList.get(selectedRow);
    }
    
    private void initWindow(){
        supplier = new ViewSupplierDetailsWindow(selectedItem);
        category = new ViewCategoryDetailsWindow(selectedItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewItemDetails_panel = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        description_label = new javax.swing.JLabel();
        supplier_label = new javax.swing.JLabel();
        category_label = new javax.swing.JLabel();
        name_details = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description_details = new javax.swing.JTextArea();
        supplier_details = new javax.swing.JLabel();
        category_details = new javax.swing.JLabel();
        close_button = new javax.swing.JButton();
        supplier_button = new javax.swing.JButton();
        category_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Item Details");
        setName("Form"); // NOI18N

        viewItemDetails_panel.setName("viewItemDetails_panel"); // NOI18N

        name_label.setText("Name:");
        name_label.setName("name_label"); // NOI18N

        description_label.setText("Description:");
        description_label.setName("description_label"); // NOI18N

        supplier_label.setText("Supplier:");
        supplier_label.setName("supplier_label"); // NOI18N

        category_label.setText("Category:");
        category_label.setName("category_label"); // NOI18N

        name_details.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        name_details.setName("name_details"); // NOI18N

        jScrollPane1.setEnabled(false);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        description_details.setEditable(false);
        description_details.setColumns(20);
        description_details.setLineWrap(true);
        description_details.setRows(5);
        description_details.setName("description_details"); // NOI18N
        jScrollPane1.setViewportView(description_details);

        supplier_details.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        supplier_details.setName("supplier_details"); // NOI18N

        category_details.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        category_details.setName("category_details"); // NOI18N

        close_button.setText("Close");
        close_button.setName("close_button"); // NOI18N
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });

        supplier_button.setText("More...");
        supplier_button.setName("supplier_button"); // NOI18N
        supplier_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_buttonActionPerformed(evt);
            }
        });

        category_button.setText("More...");
        category_button.setName("category_button"); // NOI18N
        category_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewItemDetails_panelLayout = new javax.swing.GroupLayout(viewItemDetails_panel);
        viewItemDetails_panel.setLayout(viewItemDetails_panelLayout);
        viewItemDetails_panelLayout.setHorizontalGroup(
            viewItemDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewItemDetails_panelLayout.createSequentialGroup()
                .addGroup(viewItemDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(viewItemDetails_panelLayout.createSequentialGroup()
                        .addComponent(close_button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(viewItemDetails_panelLayout.createSequentialGroup()
                        .addGroup(viewItemDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewItemDetails_panelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(viewItemDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(supplier_label, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(category_label, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewItemDetails_panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(description_label, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(viewItemDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(viewItemDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(name_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                            .addGroup(viewItemDetails_panelLayout.createSequentialGroup()
                                .addGroup(viewItemDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(supplier_details, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(category_details, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(viewItemDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(supplier_button)
                                    .addComponent(category_button))))))
                .addGap(30, 30, 30))
        );
        viewItemDetails_panelLayout.setVerticalGroup(
            viewItemDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewItemDetails_panelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(viewItemDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_label)
                    .addComponent(name_details, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(viewItemDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(description_label))
                .addGap(21, 21, 21)
                .addGroup(viewItemDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(supplier_label)
                    .addComponent(supplier_details, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplier_button))
                .addGroup(viewItemDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewItemDetails_panelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(viewItemDetails_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(category_label)
                            .addComponent(category_details, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewItemDetails_panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(category_button)))
                .addGap(28, 28, 28)
                .addComponent(close_button)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewItemDetails_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewItemDetails_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supplier_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_buttonActionPerformed
        if(!supplier.isVisible())
            supplier.setVisible(true);
        supplier.setAlwaysOnTop(true);
        supplier.setAlwaysOnTop(false);
    }//GEN-LAST:event_supplier_buttonActionPerformed

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_close_buttonActionPerformed

    private void category_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_buttonActionPerformed
        if(!category.isVisible())
            category.setVisible(true);
        category.setAlwaysOnTop(true);
        category.setAlwaysOnTop(false);
    }//GEN-LAST:event_category_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton category_button;
    private javax.swing.JLabel category_details;
    private javax.swing.JLabel category_label;
    private javax.swing.JButton close_button;
    private javax.swing.JTextArea description_details;
    private javax.swing.JLabel description_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name_details;
    private javax.swing.JLabel name_label;
    private javax.swing.JButton supplier_button;
    private javax.swing.JLabel supplier_details;
    private javax.swing.JLabel supplier_label;
    private javax.swing.JPanel viewItemDetails_panel;
    // End of variables declaration//GEN-END:variables

    @Override
    public Map getFields() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
